#!/usr/bin/env python3
import sys
import collections


class SolutionStats:
    def __init__(self):
        self.count = 0
        self.places = [0] * 4


def main():
    filename = sys.argv[1]
    all_stats = {}
    num_games = 0
    with open(filename) as reader:
        for i, line in enumerate(reader.readlines()):
            place = i % 5
            if place == 0:  # Header.
                num_games += 1
            else:
                solution, score, _ = line.split()
                stats = all_stats.setdefault(solution, SolutionStats())
                stats.count += 1
                stats.places[place - 1] += 1
    print(num_games, 'games')
    print('{:<22} {:>4} {:>4} {:>4} {:>4}'.format(
        'solution', '1', '2', '3', '4'))
    for solution, stats in all_stats.items():
        print('{:<22} {:>4.1f} {:>4.1f} {:>4.1f} {:>4.1f}'.format(
            solution, *[p / stats.count for p in stats.places]))


if __name__ == '__main__':
    main()
