#!/bin/bash -e

cd "$(dirname "$0")/.."

GAME=/tmp/game.txt
STACKS=target/out.stacks
GRAPH=target/graph.svg
STRATEGY=target/latest

if [[ "$STRATEGY" -nt "$GAME" ]]; then
  echo "run the following command to create $GAME"
  echo "./script/build --release && ./script/local-runner 2>'$GAME'"
  exit 1
fi

rm -f "$STACKS"
sudo dtrace -c "./$STRATEGY" -n 'profile-997 /execname == "strategy"/ { @[ustack(100)] = count(); }' -o "$STACKS" <"$GAME" >/dev/null
~/Code/FlameGraph/stackcollapse.pl "$STACKS" | ~/Code/FlameGraph/flamegraph.pl >"$GRAPH"
open -a 'Google Chrome' "$GRAPH"
