#!/usr/bin/env python3
import json
import sys


def main():
    solutions = sys.argv[1:5]
    filename = sys.argv[5]
    with open(filename) as reader:
        scores = json.load(reader)
    total = sum(scores.values())
    print('{:<22} {:>10} {:>10}'.format('solution', 'score', 'total %'))
    for solution, score in sorted(scores.items(), key=lambda item: -item[1]):
        solution = solutions[int(solution) - 1]
        print('{:<22} {:>10} {:>10.1f}'.format(solution, score,
                                               score / total * 100))


if __name__ == '__main__':
    main()
