#!/bin/bash -e

cd "$(dirname "$0")/.."

OUTPUT_DIR="target/submission"
OUTPUT_FILE="target/submission.rs"
rm -rf "$OUTPUT_DIR" "$OUTPUT_FILE"
mkdir -p "$OUTPUT_DIR"
cp -r src/* "$OUTPUT_DIR"

VERSION="$(git rev-parse --short HEAD)"
sed -i '' -- 's/"DEV"/"'"$VERSION"'"/g' "$OUTPUT_DIR/version.rs"

cargo run -p expand-mods -- "$OUTPUT_DIR/main.rs" | rustfmt >"$OUTPUT_FILE"
echo "Created $OUTPUT_FILE"
