#!/bin/bash -e

cd "$(dirname "$0")/.."

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

TOURNAMENT=/var/tmp/tournament.txt
rm -rf "$TOURNAMENT"

for round in $(seq 1 "$1"); do
  echo "round $round"

  export GAME_LOG_LOCATION=/var/tmp/game_log.txt
  export GAME_TICKS="${GAME_TICKS:-7500}"
  ./vendor/miniaicups/agario/server_runner &
  sleep 0.3

  strategies=("${@:2:4}")
  for i in {1..4}; do
    strategy="${strategies[i - 1]}"
    socat tcp:127.0.0.1:8000 \
      exec:"./script/client-runner '$i' '$strategy'" &
    echo "solution $i pid $!"
  done
  wait

  ./script/report-scores "${strategies[@]}" /var/tmp/scores.json | tee -a "$TOURNAMENT"
done

./script/analyze-tournament "$TOURNAMENT"
